### ISSUE TITLE
Bundle in subfolder

### ISSUE THREAD

**Issue by mewcrow** [gurgeous/bust-a-gem#21]
Hi!
I have separate dirs in my project. For api and frontend. So gemfile is located in subdirectory. Is there way to specify this subfolder to rip tags?

**Comment by gurgeous** [comment]
Hm, good question. I'm a bit rusty on bustagem so I had to go back and read the source myself. I don't think this will be particularly easy. Probably the easiest way is to open each folder individually in vscode and do the ripping.

You can also just rebuild from the command line: `ripper-tags ...`. A script would help. Lately I've been wondering if I should rip the tags stuff out of bustagem entirely. I mostly use it for opening gems since the vscode ruby extension is such a mess.

Closing for now. Let me know if you disagree. Thanks @mewcrow!
